# Generated by Django 4.1.4 on 2022-12-14 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statusapp', '0001_initial'),
        ('categoryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='tizer title')),
                ('description', models.TextField(verbose_name='tizer description')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='tizer author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoryapp.category', verbose_name='tizer category')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='statusapp.status', verbose_name='tizer status')),
            ],
        ),
    ]
