# Generated by Django 4.1.4 on 2022-12-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0001_initial'),
        ('tizerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tizer',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='statusapp.status', verbose_name='tizer status'),
        ),
    ]
