# Generated by Django 4.1.4 on 2022-12-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('paid', 'Paid'), ('rejected', 'Rejected')], max_length=64, unique=True, verbose_name='status name')),
            ],
        ),
    ]
